// SB244 Vote Data - Kansas Legislature
// Source: Kansas Legislature vote records, Jan 28 & Feb 18, 2026
// Vote recorded as the FINAL veto override vote (most decisive)
// Nay voters = HEROES who stood against this bill

const SB244_VOTES = {
  // ============================================================
  // KANSAS HOUSE OF REPRESENTATIVES
  // Veto Override: Yea 87, Nay 37 (Feb 18, 2026)
  // ============================================================
  house: [
    // NAY VOTERS (voted AGAINST SB244 - stood with trans Kansans)
    { name: "Alcala", firstName: "Linda", chamber: "House", vote: "NAY", party: "D" },
    { name: "Amyx", firstName: "John", chamber: "House", vote: "NAY", party: "D" },
    { name: "Ballard", firstName: "Kathy", chamber: "House", vote: "NAY", party: "D" },
    { name: "Boatman", firstName: "Abi", chamber: "House", vote: "NAY", party: "D" },
    { name: "Brownlee Paige", firstName: "Valdenia", chamber: "House", vote: "NAY", party: "D" },
    { name: "Carlin", firstName: "Dennis", chamber: "House", vote: "NAY", party: "D" },
    { name: "Carmichael", firstName: "Francis", chamber: "House", vote: "NAY", party: "D" },
    { name: "Carr", firstName: "Pam", chamber: "House", vote: "NAY", party: "D" },
    { name: "Curtis", firstName: "Jason", chamber: "House", vote: "NAY", party: "D" },
    { name: "Featherston", firstName: "Sean", chamber: "House", vote: "NAY", party: "D" },
    { name: "Haskins", firstName: "Trevor", chamber: "House", vote: "NAY", party: "D" },
    { name: "Hoye", firstName: "Marvin", chamber: "House", vote: "NAY", party: "D" },
    { name: "Martinez", firstName: "Christina", chamber: "House", vote: "NAY", party: "D" },
    { name: "McDonald", firstName: "Brett", chamber: "House", vote: "NAY", party: "D" },
    { name: "Melton", firstName: "Dave", chamber: "House", vote: "NAY", party: "D" },
    { name: "Meyer", firstName: "Tory", chamber: "House", vote: "NAY", party: "D" },
    { name: "Mosley", firstName: "Stephanie", chamber: "House", vote: "NAY", party: "D" },
    { name: "Neighbor", firstName: "Mike", chamber: "House", vote: "NAY", party: "D" },
    { name: "Ohaebosim", firstName: "Rui", chamber: "House", vote: "NAY", party: "D" },
    { name: "Oropeza", firstName: "Mari-Lynn", chamber: "House", vote: "NAY", party: "D" },
    { name: "Osman", firstName: "Dan", chamber: "House", vote: "NAY", party: "D" },
    { name: "Ousley", firstName: "Ponka-We", chamber: "House", vote: "NAY", party: "D" },
    { name: "Poskin", firstName: "Jack", chamber: "House", vote: "NAY", party: "D" },
    { name: "Ruiz", firstName: "Louis", chamber: "House", vote: "NAY", party: "D" },
    { name: "Ruiz", firstName: "Susan", chamber: "House", vote: "NAY", party: "D" },
    { name: "Sawyer", firstName: "Tom", chamber: "House", vote: "NAY", party: "D" },
    { name: "Sawyer Clayton", firstName: "Jennifer", chamber: "House", vote: "NAY", party: "D" },
    { name: "Schlingensiepen", firstName: "Cindy", chamber: "House", vote: "NAY", party: "D" },
    { name: "Schreiber", firstName: "Emily", chamber: "House", vote: "NAY", party: "D" },
    { name: "Simmons", firstName: "Henry", chamber: "House", vote: "NAY", party: "D" },
    { name: "Stogsdill", firstName: "Ann", chamber: "House", vote: "NAY", party: "D" },
    { name: "Vaughn", firstName: "Vic", chamber: "House", vote: "NAY", party: "D" },
    { name: "Weigel", firstName: "Tim", chamber: "House", vote: "NAY", party: "D" },
    { name: "Wikle", firstName: "Susan", chamber: "House", vote: "NAY", party: "D" },
    { name: "Woodard", firstName: "John", chamber: "House", vote: "NAY", party: "D" },
    { name: "Xu", firstName: "Henry", chamber: "House", vote: "NAY", party: "D" },

    // YEA VOTERS (voted FOR SB244 - harmed trans Kansans)
    { name: "Anderson", firstName: "Brett", chamber: "House", vote: "YEA", party: "R" },
    { name: "Awerkamp", firstName: "Emil", chamber: "House", vote: "YEA", party: "R" },
    { name: "Barrett", firstName: "Barb", chamber: "House", vote: "YEA", party: "R" },
    { name: "Bergkamp", firstName: "Blake", chamber: "House", vote: "YEA", party: "R" },
    { name: "Bergquist", firstName: "Shannon", chamber: "House", vote: "YEA", party: "R" },
    { name: "Blex", firstName: "John", chamber: "House", vote: "YEA", party: "R" },
    { name: "Bloom", firstName: "Susan", chamber: "House", vote: "YEA", party: "R" },
    { name: "Borjon", firstName: "Bill", chamber: "House", vote: "YEA", party: "R" },
    { name: "Brantley", firstName: "Chuck", chamber: "House", vote: "YEA", party: "R" },
    { name: "Brunk", firstName: "Steve", chamber: "House", vote: "YEA", party: "R" },
    { name: "Bryce", firstName: "Renee", chamber: "House", vote: "YEA", party: "R" },
    { name: "Buehler", firstName: "Will", chamber: "House", vote: "YEA", party: "R" },
    { name: "Butler", firstName: "Steven", chamber: "House", vote: "YEA", party: "R" },
    { name: "Caiharr", firstName: "Randy", chamber: "House", vote: "YEA", party: "R" },
    { name: "Carpenter", firstName: "Bill", chamber: "House", vote: "YEA", party: "R" },
    { name: "Carpenter", firstName: "Will", chamber: "House", vote: "YEA", party: "R" },
    { name: "Chauncey", firstName: "Scott", chamber: "House", vote: "YEA", party: "R" },
    { name: "Collins", firstName: "Randy", chamber: "House", vote: "YEA", party: "R" },
    { name: "Corbet", firstName: "Tom", chamber: "House", vote: "YEA", party: "R" },
    { name: "Croft", firstName: "Chris", chamber: "House", vote: "YEA", party: "R" },
    { name: "Delperdang", firstName: "Jesse", chamber: "House", vote: "YEA", party: "R" },
    { name: "Droge", firstName: "Kent", chamber: "House", vote: "YEA", party: "R" },
    { name: "Ellis", firstName: "Kyle", chamber: "House", vote: "YEA", party: "R" },
    { name: "Esau", firstName: "Susan", chamber: "House", vote: "YEA", party: "R" },
    { name: "Essex", firstName: "Michael", chamber: "House", vote: "YEA", party: "R" },
    { name: "Estes", firstName: "Ron", chamber: "House", vote: "YEA", party: "R" },
    { name: "Fairchild", firstName: "Ron", chamber: "House", vote: "YEA", party: "R" },
    { name: "Francis", firstName: "Ron", chamber: "House", vote: "YEA", party: "R" },
    { name: "Gardner", firstName: "Randy", chamber: "House", vote: "YEA", party: "R" },
    { name: "Goddard", firstName: "Mike", chamber: "House", vote: "YEA", party: "R" },
    { name: "Goetz", firstName: "Steve", chamber: "House", vote: "YEA", party: "R" },
    { name: "Hawkins", firstName: "Clark", chamber: "House", vote: "YEA", party: "R" },
    { name: "Helwig", firstName: "Troy", chamber: "House", vote: "YEA", party: "R" },
    { name: "Hoffman", firstName: "Steve", chamber: "House", vote: "YEA", party: "R" },
    { name: "Hoheisel", firstName: "Jerry", chamber: "House", vote: "YEA", party: "R" },
    { name: "Howe", firstName: "Jim", chamber: "House", vote: "YEA", party: "R" },
    { name: "Howell", firstName: "Jack", chamber: "House", vote: "YEA", party: "R" },
    { name: "Howerton", firstName: "Nick", chamber: "House", vote: "YEA", party: "R" },
    { name: "Huebert", firstName: "John", chamber: "House", vote: "YEA", party: "R" },
    { name: "Humphries", firstName: "Susan", chamber: "House", vote: "YEA", party: "R" },
    { name: "James", firstName: "Tory", chamber: "House", vote: "YEA", party: "R" },
    { name: "Kessler", firstName: "Don", chamber: "House", vote: "YEA", party: "R" },
    { name: "King", firstName: "Larry", chamber: "House", vote: "YEA", party: "R" },
    { name: "Lewis", firstName: "Bob", chamber: "House", vote: "YEA", party: "R" },
    { name: "Long", firstName: "Mike", chamber: "House", vote: "YEA", party: "R" },
    { name: "McNorton", firstName: "Tory", chamber: "House", vote: "YEA", party: "R" },
    { name: "Minnix", firstName: "Greg", chamber: "House", vote: "YEA", party: "R" },
    { name: "Moser", firstName: "Troy", chamber: "House", vote: "YEA", party: "R" },
    { name: "Neelly", firstName: "Jim", chamber: "House", vote: "YEA", party: "R" },
    { name: "Pickert", firstName: "Brad", chamber: "House", vote: "YEA", party: "R" },
    { name: "Pishny", firstName: "Diana", chamber: "House", vote: "YEA", party: "R" },
    { name: "Poetter Parshall", firstName: "Jennifer", chamber: "House", vote: "YEA", party: "R" },
    { name: "Proctor", firstName: "Monica", chamber: "House", vote: "YEA", party: "R" },
    { name: "Rahjes", firstName: "Ken", chamber: "House", vote: "YEA", party: "R" },
    { name: "Reavis", firstName: "Jesse", chamber: "House", vote: "YEA", party: "R" },
    { name: "Resman", firstName: "Kyle", chamber: "House", vote: "YEA", party: "R" },
    { name: "Rhiley", firstName: "Kristie", chamber: "House", vote: "YEA", party: "R" },
    { name: "Roth", firstName: "Kent", chamber: "House", vote: "YEA", party: "R" },
    { name: "Ruiz", firstName: "Victor", chamber: "House", vote: "YEA", party: "R" },
    { name: "Ryckman", firstName: "Dan", chamber: "House", vote: "YEA", party: "R" },
    { name: "Samsel", firstName: "A.J.", chamber: "House", vote: "YEA", party: "R" },
    { name: "Seiwert", firstName: "Ken", chamber: "House", vote: "YEA", party: "R" },
    { name: "Sloan", firstName: "John", chamber: "House", vote: "YEA", party: "R" },
    { name: "Smith", firstName: "Adam", chamber: "House", vote: "YEA", party: "R" },
    { name: "Smith", firstName: "Tory", chamber: "House", vote: "YEA", party: "R" },
    { name: "Stoll", firstName: "Kent", chamber: "House", vote: "YEA", party: "R" },
    { name: "Tarwater", firstName: "John", chamber: "House", vote: "YEA", party: "R" },
    { name: "Thomas", firstName: "Steve", chamber: "House", vote: "YEA", party: "R" },
    { name: "Thompson", firstName: "Dave", chamber: "House", vote: "YEA", party: "R" },
    { name: "Tietze", firstName: "Joe", chamber: "House", vote: "YEA", party: "R" },
    { name: "Turner", firstName: "Kyle", chamber: "House", vote: "YEA", party: "R" },
    { name: "Vickrey", firstName: "Jan", chamber: "House", vote: "YEA", party: "R" },
    { name: "Waymaster", firstName: "Louis", chamber: "House", vote: "YEA", party: "R" },
    { name: "Wheeler", firstName: "Brian", chamber: "House", vote: "YEA", party: "R" },
    { name: "Whipple", firstName: "Mike", chamber: "House", vote: "YEA", party: "R" },
    { name: "Wolfe Moore", firstName: "Susan", chamber: "House", vote: "YEA", party: "R" },
    { name: "Wrenner", firstName: "Kristy", chamber: "House", vote: "YEA", party: "R" },
    { name: "Yakym", firstName: "Randy", chamber: "House", vote: "YEA", party: "R" },
  ],

  // ============================================================
  // KANSAS SENATE
  // Veto Override: Yea 31, Nay 9 (Feb 17, 2026)
  // ============================================================
  senate: [
    // NAY VOTERS (voted AGAINST SB244)
    { name: "Braun", firstName: "Cindy", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Dietrich", firstName: "Pat", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Holscher", firstName: "Ethan", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Peck", firstName: "Oletha", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Pittman", firstName: "Tom", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Ware", firstName: "David", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Wilborn", firstName: "Mike", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Woods", firstName: "Mary Jo", chamber: "Senate", vote: "NAY", party: "D" },
    { name: "Xu", firstName: "Helen", chamber: "Senate", vote: "NAY", party: "D" },

    // YEA VOTERS (voted FOR SB244)
    { name: "Alley", firstName: "Renee", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Billinger", firstName: "Rick", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Bowers", firstName: "Carolyn", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Claeys", firstName: "Les", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Corson", firstName: "Kristen", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Doxon", firstName: "John", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Erickson", firstName: "Molly", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Fagg", firstName: "Tyler", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Faust-Goudeau", firstName: "Oletha", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Francisco", firstName: "Marci", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Haley", firstName: "Tim", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Hilderbrand", firstName: "Rick", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Holland", firstName: "Caryn", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Kloos", firstName: "Mark", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Longbine", firstName: "Jeff", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Lynn", firstName: "Julia", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Masterson", firstName: "Ty", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "McGinn", firstName: "Kellie", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Miller", firstName: "Richard", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "O'Shea", firstName: "Dennis", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Olson", firstName: "Gene", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Peck", firstName: "Mike", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Petersen", firstName: "Jeff", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Rucker", firstName: "Brenda", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Sharp", firstName: "Larry", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Straub", firstName: "Mike", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Suellentrop", firstName: "Gene", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Thomas", firstName: "Randy", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Thompson", firstName: "Jeff", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Tyson", firstName: "Tim", chamber: "Senate", vote: "YEA", party: "R" },
    { name: "Warren", firstName: "Kirk", chamber: "Senate", vote: "YEA", party: "R" },
  ]
};

// Pro-trans organizations to redirect donations to
const ORGANIZATIONS = [
  {
    name: "ACLU of Kansas",
    description: "Currently suing to block SB244 in court",
    url: "https://www.aclukansas.org/en/donate",
    logo: "⚖️"
  },
  {
    name: "Kansas Equality Coalition",
    description: "Kansas-based LGBTQ+ advocacy organization",
    url: "https://www.ksequality.org/donate",
    logo: "🏳️‍⚧️"
  },
  {
    name: "Human Rights Campaign",
    description: "Nation's largest LGBTQ+ civil rights org",
    url: "https://www.hrc.org/donate",
    logo: "💛"
  }
];
